# NOTE: rails.yml は repository毎に設定する
inherit_from:
  - .rubocop_todo.yml
  - config/exclude.yml
  - config/enabled.yml
  - config/disabled.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3
  DefaultFormatter: progress
