# NOTE: rails.yml は repository毎に設定する
inherit_from:
  - .rubocop_todo.yml
  - config/enabled.yml
  - config/disabled.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3
  DefaultFormatter: progress
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'doc/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
